version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/user/src/app
    command: sh -c "cd react-practice && yarn start"
    ports:
      - "8000:8000"
